### ISSUE TITLE
-Wstatic-in-inline warnings for 'director' in shd-interposer.c

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#717]
Trying to work out how to best resolve clang warning -Wstatic-in-inline in [shd-interposer.c](https://github.com/shadow/shadow/blob/35877198b38684a4d98e42bebd22b6697b504c80/src/preload/shd-interposer.c)

@6dc89462d25594967fb3d0ea16bac535668cddef (roughly current HEAD, with -Werror and some other unmerged fixes)

There are tenish warnings like:
```
$ CC=clang ./setup build --clean
...
/home/jnewsome/src/shadow/src/preload/shd-preload-defs.h:133:1: error: static variable 'director' is used in an inline function with external linkage [-Werror,-Wstatic-in-inline]
PRELOADDEF(return, int, putchar, (int a), a);
^
/home/jnewsome/src/shadow/src/preload/shd-interposer.c:217:9: note: expanded from macro 'PRELOADDEF'
        ENSURE(functionname); \
        ^
/home/jnewsome/src/shadow/src/preload/shd-interposer.c:67:9: note: expanded from macro 'ENSURE'
    if(!director.next.func) { \
        ^
/home/jnewsome/src/shadow/src/preload/shd-interposer.c:84:21: note: 'director' declared here
static FuncDirector director;
...
```

Looking at one of these, `pthread_equals`, it turns out that `pthread.h` has
both an extern declaration, and an extern *inline* definition:

```
extern int pthread_equal (pthread_t __thread1, pthread_t __thread2)
  __THROW __attribute__ ((__const__));

...
__extern_inline int
__NTH (pthread_equal (pthread_t __thread1, pthread_t __thread2))
{
  return __thread1 == __thread2;
}
```

The first thing I want to determine is whether there's a bigger problem here of
having multiple definitions (the inline definition in the header, and shadow's
override) of `pthread_equal`. In a small test program, using the "normal"
`inline` keyword results in a complaint about multiple definitions as expected.
However, using `__extern_inline`, which expands to `extern __inline
__attribute__ ((__gnu_inline__))`, doesn't.

The latter (i.e. shadow's override) seems to get called instead of the inline
version, but I can't find any documentation about this behavior and hence
whether there's any guarantee that's what will happen. In the case of
`pthread_equal`, the emulated version is equivalent to the inline version, so
it doesn't matter.  What about the others?

* `pthread_equal`: /usr/include/pthread.h.
  Equivalent to `process_emu_pthread_equal`, so ok if inlined version is used.
* `vprintf`: `/usr/include/stdio.h` -> `/usr/include/x86_64-linux-gnu/bits/stdio.h` -> `/usr/include/x86_64-linux-gnu/bits/stdio.h`.
  Looks like it just calls vfprintf, which should let us still intercept it.
* `putchar`: `/usr/include/stdio.h` -> `/usr/include/x86_64-linux-gnu/bits/stdio.h` -> `/usr/include/x86_64-linux-gnu/bits/stdio.h`
  Calls an internal helper `_IO_getc`, which appears to not be intercepted by shadow.

So of these only `putchar` looks like the inlined version might circumvent
shadow.  It looks like the internal helper it calls
[`_IO_getc`](https://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/baselib--io-getc-3.html)
is actually defined in some standard, so maybe there's some hope of being able
to identify and cover most of these.

Popping up a level, I suspect the issue that the compiler *is* actually trying
to warn us about isn't a problem. I imagine that it's trying to catch the case
where the inline implementation of a function refers to a static variable. 
In our case only the non-inline version refers to a static variable.

One other question raised while looking at this - the static `director`
object isn't thread-local, isn't const, and isn't protected by any mutex.
IIUC shadow's worker threads are native, and so could concurrently write to it.
I believe this is undefined behavior.

TODO:

- [X] Confirm that the static variable access in these function isn't actually a problem. Maybe try a clang mailing list. DONEish. No response on mailing list, but seems clear that it's not.
- [X] If it's really not a problem, suppress that warning for this file. If it is a problem, refactor to avoid it. Already confirmed that moving the saved function pointers to function-scoped statics instead of a global static makes the warning go away, but I'd rather not move to that if there's no real reason to. DONE: #721 
- [X] Check my understanding re undefined behavior from accessing the static `director` from concurrent worker pthreads. If it is an issue, the pointers could be moved to thread-local storage. The counters should probably be protected by a mutex, though. DONEish. Orthogonal to this bug; opened #724 to track.
- [X] Open another bug for the potential `getchar` issue. DONE: #739

**Comment by sporksmith** [comment]
Clang IRC channel recommended posting to clang-dev. Did so last week, but crickets so far. https://lists.llvm.org/pipermail/cfe-dev/2020-February/064611.html
