### ISSUE TITLE
More human-readable Shadow config

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#773]
Support for a more human-readable format such as YAML would be nice as it would be easier to read/write/modify config files and would help us eventually move away from XML configuration files. This work could be split into multiple steps:

  - [x] (Merged in #803) - Create an external tool that converts between `shadow.config.xml` XML files and `shadow.config.yaml` YAML files (i.e., converts XML to YAML, and YAML to XML). 
  - [x] (Merged in #895) - Modify Shadow so that it will accept its XML configuration on stdin rather than requiring that we read it from the `shadow.config.xml` file. (It should be able to read from stdin or from a file.)
  - [x] (Merged in #972) - Convert existing tests from xml to yaml, and use the yaml2xml converter in the test cases.
  - [ ] Long term: add support to Shadow so it can natively read and understand YAML files.
  - [ ] Long term: new "options" section in the config file. Here we could specify any global options, and make it so that command line options could also instead be added to the yaml file (and Shadow internally would process the options using the same code for consistency whether the options are specified on the command line or in the config file).

As an example, the [small example in the shadow repo](https://github.com/shadow/shadow/blob/master/resource/examples/shadow.config.xml) currently looks like this in XML:

```xml
<shadow stoptime="3600">
  <topology><![CDATA[<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="isp">
      <data key="d0">0.0.0.0</data>
      <data key="d1">2251</data>
      <data key="d2">17038</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="isp" target="isp">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
  </graph>
</graphml>
]]></topology>
  <plugin id="tgen" path="~/.shadow/bin/tgen"/>
  <host id="server">
    <process plugin="tgen" starttime="1" arguments="tgen.server.graphml.xml"/>
  </host>
  <host id="client">
    <process plugin="tgen" starttime="2" arguments="tgen.client.graphml.xml"/>
  </host>
</shadow>
```

And we could convert between XML and something like this in YAML:

```yaml
options:
    - stoptime: 3600

topology:
    - graphml: "<topology><![CDATA[<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="isp">
      <data key="d0">0.0.0.0</data>
      <data key="d1">2251</data>
      <data key="d2">17038</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="isp" target="isp">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
  </graph>
</graphml>
]]></topology>"

plugins:
    - id: tgen
      path: ~/.shadow/bin/tgen

hosts:
    - id: server
      bandwidthdown: 102400
      bandwidthup: 102400                                                                                                                    
      processes:
          - plugin: tgen
            starttime: 1
            arguments: tgen.server.graphml.xml                                                                                          
    - id: client
      bandwidthdown: 102400
      bandwidthup: 102400                                                                                                                    
      processes:
          - plugin: tgen
            starttime: 2
            arguments: tgen.client.graphml.xml      
```

**NOTE:** We should continue to support graphml for the network topology graphs because we use igraph to read and to store the graph internally and to do graph operations on it (path lookups etc.). For anything but trivial examples, [the network graph I use](https://tmodel-ccs2018.github.io/data/shadow/network/atlas-lossless.201801.shadow113.graphml.xml.xz) is quite large, and I usually don't want to reproduce that in the config file. Also, I almost always use the same graph, so having a path to it works well. For trivial graphs, like the ones usually included in the examples, we will have to either read from the YAML format and then programmatically build up an igraph graph, or specify the graph in [a format that igraph understands](https://igraph.org/c/doc/igraph-Foreign.html). We chose graphml since it is common, and I don't see a reason for moving away from it now.

**Comment by sporksmith** [comment]
My experience so far is mostly with the trivial examples in the tests, probably leading to some bias. OTOH making this format "scale down" to simple examples would help a lot to make the tool more reduce the learning curve for newcomers.

> NOTE: We should continue to support graphml for the network topology graphs

Hmm, IMO that part of the config is the least human-readable/editible; particularly because of the indirection between e.g. "d6" and "packetloss".

Actually, is there a reason we couldn't just use more human-readable keys? e.g.

```
<key attr.name="packetloss" attr.type="double" for="edge" id="packetloss" />
...
<data key="packetloss">0.01</data>
```
Btw I was confused until now about why the node id's and host id's don't correspond in any way. I see now that it's [documented](https://github.com/shadow/shadow/blob/master/docs/3.2-Network-Config.md#vertices) that the nodes are actually more like ISPs, and that hosts get assigned to nodes via IP and location hints. Is there a reason not to assign hosts to nodes more explicitly? e.g.

```
  <host id="server" node="isp">
```

If it's desirable to use IPs and locations to help map hosts to nodes, e.g. perhaps when trying to model real-world networks, perhaps that could be done in a preprocessing step when generating the topology instead of inside shadow? That'd make the relationship between hosts and topology nodes a lot more obvious, as well as taking out any guess-work about the specific node each host is getting assigned to.

>  we will have to either read from the YAML format and then programmatically build up an igraph graph, or specify the graph in a format that igraph understands. We chose graphml since it is common, and I don't see a reason for moving away from it now.

Well, it being not very human readable/writable is *a* reason, but fair point it might not be reason enough to justify the effort :). Programmatically building up an igraph from our own, e.g. YAML format, doesn't sound *too* bad. Or as proposed for the config itself, writing a converter from YAML to graphml. (That said, maybe the tweaks suggested above to make the graphml more readable would be good enough to make this extra step not worth it)

**Comment by robgjansen** [comment]
> Actually, is there a reason we couldn't just use more human-readable keys? e.g.
>
> ```
> <key attr.name="packetloss" attr.type="double" for="edge" id="packetloss" />
> ...
> <data key="packetloss">0.01</data>
> ```

I generated the graphml with python's `networkx` package, and for whatever reason, they ignore attribute names that I set in python and instead assign their own using the d0, d1 etc. naming scheme. I believe we should be able to change those in graphs we edit manually (without python) and it should still be valid graphml. And I suppose we could try to find some other graphing library rather than using networkx when generating large graphs.

---

> Is there a reason not to assign hosts to nodes more explicitly? e.g.
>
>```
> <host id="server" node="isp">
> ```

I think this would be a useful improvement for small graphs constructed manually. 

In [larger, more realistic Internet graphs](https://tmodel-ccs2018.github.io/data/shadow/network/atlas-lossless.201801.shadow113.graphml.xml.xz), each node in the topology is assigned an IP address as the node id. (We need to guarantee the id is unique, and IP addresses are a fine way to do that while also meaningfully representing the network we are modeling.) For example:

```
    <node id="2.235.244.95">
      <data key="d1">2.235.244.95</data>
      <data key="d2">3177664</data>
      <data key="d3">IT</data>
      <data key="d4">3901</data>
      <data key="d5">1367</data>
    </node>
```

The way to assign a host to this node currently is:
```
<host id="server" iphint="2.235.244.95">
```
which should match on data key 'd1'. Adding another option that matches on the node id seems like a good idea. In this case it would be:
```
<host id="server" node="2.235.244.95">
```

---

> e.g. perhaps when trying to model real-world networks, perhaps that could be done in a preprocessing step when generating the topology instead of inside shadow?

I think you mean when generating the *shadow config file* not the network topology.

Preprocessing is possible, but it's another step and also introduces a dependency in the modeling process.
  - You would need to have the topology present when generating the shadow config, and the tool that generates the shadow config would need to read and process the graph at the same time. This is a memory intensive process and it would be nice if we didn't ask users to do that step (currently in python).
  - The shadow config file may become invalid when you change the network topology; you wouldn't be able to swap between network configs.
An advantage of the current approach is that the shadow config and network topologies are somewhat independent, which makes things a bit more flexible.

---

> Well, it being not very human readable/writable is a reason, but fair point it might not be reason enough to justify the effort :).

If we had more informative keys rather than d0, d1, d2, ..., then I actually find the graphml format *more* useful than the YAML format for graphs, because it's more explicit about the data and attributes. However, I also see the value in YAML, and supporting a common format for the config and the graph has benefits.

So yeah, I agree that in the short term we should probably prioritize making the other above improvements over changing the graph format.

**Comment by robgjansen** [comment]
TGen also uses graphml for it's configuration files. I generally tend to edit those manually much more often, and we could also work on switching those to YAML.

**Comment by sporksmith** [comment]
Thanks for the explanations! That all makes sense. It sounds like this could be broken up into fairly independent issues:

- Support YAML for Shadow config
- Support YAML for TGen config
- Make topology graphml more readable
  - Add support for a "node" attribute on hosts, pointing to a node id.
  - Fix our examples and/or topology generation tools to generate more informative keys than "d0", "d1", ...

I still think it could also be worth the extra clarity gained by using a more application-specific schema for graphs (whether a specialized XML schema or YAML) and then compiling to graphml (maybe inside Shadow itself). I agree though that the other goals above have a clearer cost/benefit, so it makes sense to focus on those first.

**Comment by robgjansen** [comment]
OK. I'll keep this issue as the parent for "human readable" configs, and split things into multiple new issues.

**Comment by florian-vuillemot** [comment]
If I understand correctly, this point: "Convert existing tests from XML to YAML, and use the yaml2xml converter in the test cases.", the only action to do is to go on each shadow XML file in the `test` directory and convert them to YAML. So, we will definitively replace the XML configurations files to use YAML only.

* If this is the case, should I also update the doc to explain the `yaml2xml` tool and update examples ?
* Should I create a new temporary file or just pipe the `yaml2xml` output on each test ?
* Do you agree with a PR by a directory update to limit the merging ?

**Comment by robgjansen** [comment]
Here is what I was thinking. This example is for the `src/test/bind` test, but would be applied to all tests:

- run `src/tools/convert.py xml2yaml bind.test.shadow.config.xml > bind.test.shadow.config.yml`
- remove `bind.test.shadow.config.xml`
- Change the test spec in `CMakeLists.txt` to convert back to xml on the fly

e.g. something like this (NOT tested)
```cmake
add_test(NAME bind-shadow-ptrace COMMAND python ${CMAKE_SOURCE_DIR}/tools/convert.py ${CMAKE_CURRENT_SOURCE_DIR}/bind.test.shadow.config.yml | ${CMAKE_BINARY_DIR}/src/main/shadow --interpose-method=ptrace -l debug -d bind.shadow-ptrace.data -)
```

- don't use temp files, just convert on-the-fly and use pipe
- I'm not sure if `|` is correct in the above, or if there is a different way to pipe with CMake
- I'm not sure what docs we have about the tests, but if we have some that reference the xml files, those should be updated to refer to the yml files
- I don't understand what you mean by "a PR by a directory update". Just modify the files directly as above, don't create new test directories. We want to make sure we track the changes along with the rest of the git history.

**Comment by robgjansen** [comment]
@florian-vuillemot I forgot to mention: it would be a good idea to submit a draft PR with an example of changing only one test first so we can look that over. Then if we are happy you can continue doing the rest of the test cases and push those extra commits to the PR. That way you don't end up doing a bunch of work that you might have to change later.

**Comment by stevenengler** [comment]
We have moved our configuration and command-line parsing to Rust/YAML, so I think we can close this now. We still use GraphML, but we have a separate issue for investigating different topology formats (https://github.com/shadow/shadow/issues/778)
